import yaml
from pathlib import Path
from urllib.parse import urlparse
from collections import Counter

def bootstrap_from_txt(txt_path: Path, output_yaml: Path, rejected_txt: Path):
    """
    Lee un archivo de texto con URLs, filtra archivos no-HTML y redes sociales,
    y genera un archivo YAML de proyecto con reglas de tópicos inferidas.
    """
    if not txt_path.exists():
        return False, 0, 0

    with open(txt_path, 'r', encoding='utf-8') as f:
        urls = [line.strip() for line in f if line.strip()]

    valid_urls = []
    rejected_urls = []

    # Filtros de exclusión (Extensiones de archivos y redes sociales)
    rejected_extensions = ('.pdf', '.docx', '.doc', '.xlsx', '.xls', '.zip', '.rar', '.png', '.jpg', '.jpeg', '.gif', '.mp4', '.avi', '.xhtml')
    rejected_domains = ('youtube.com', 'youtu.be', 'facebook.com', 'instagram.com', 'tiktok.com', 'x.com', 'twitter.com', 'linkedin.com')

    for url in urls:
        try:
            parsed = urlparse(url)
            path_lower = parsed.path.lower()
            netloc_lower = parsed.netloc.lower()

            is_rejected = False
            if path_lower.endswith(rejected_extensions):
                is_rejected = True
            elif any(d in netloc_lower for d in rejected_domains):
                is_rejected = True

            if is_rejected:
                rejected_urls.append(url)
            else:
                valid_urls.append(url)
        except Exception:
            rejected_urls.append(url)

    # Guardar rechazados para revisión del usuario
    if rejected_urls:
        with open(rejected_txt, 'w', encoding='utf-8') as f:
            for u in rejected_urls:
                f.write(u + '\n')

    if not valid_urls:
        return False, 0, len(rejected_urls)

    # 1. Inferir Dominio Principal (el más común)
    domains = [urlparse(u).netloc for u in valid_urls]
    primary_domain = Counter(domains).most_common(1)[0][0] if domains else "example.com"

    # 2. Inferir Reglas de Tópicos por Patrones de Ruta
    paths = [urlparse(u).path for u in valid_urls if urlparse(u).path.strip('/')]
    segments = []
    
    # Segmentos que no aportan valor semántico para agrupar
    generic_segments = {'index.php', 'wp-content', 'wp-includes', 'templates', 'images', 'archivos_tecnicos'}

    for p in paths:
        parts = [part for part in p.split('/') if part]
        if not parts:
            continue
            
        # Algoritmo de extracción de segmento útil: saltamos los genéricos
        useful_parts = []
        for part in parts:
            if part in generic_segments:
                useful_parts.append(part)
                continue # Seguimos buscando el siguiente nivel real
            else:
                useful_parts.append(part)
                break # Encontramos el primer nivel real, paramos aquí
        
        if useful_parts:
            segments.append("/" + "/".join(useful_parts))

    # Tomamos los segmentos que se repiten para crear reglas de agrupación
    common_segments = [seg for seg, count in Counter(segments).most_common(12) if count > 1]
    
    topic_rules = []
    for seg in sorted(common_segments, key=len, reverse=True): # De más específico a más general
        slug = seg.strip('/').replace('index.php/', '').replace('.php', '').replace('-', '_').replace('/', '_')
        if not slug: slug = "general"
        topic_rules.append({
            "path_prefix": seg,
            "topic_slug": slug
        })

    # Catch-all final
    topic_rules.append({
        "path_prefix": "/",
        "topic_slug": "general_y_varios"
    })

    # 3. Construir Configuración
    project_id = primary_domain.split('.')[0].replace('www', '').strip('.')
    if not project_id: project_id = "nuevo_proyecto"

    config_dict = {
        "project_id": project_id,
        "name": f"Autogenerated - {primary_domain}",
        "primary_domain": primary_domain,
        "user_agent": "NotebookLM-Doc-Sync/1.0 (+https://github.com/CGary/notebooklm-doc-sync)",
        "contact_url": "https://github.com/CGary/notebooklm-doc-sync",
        "rate_limit_per_host_rps": 1.0,
        "ssl_verify": False,
        "topic_rules": topic_rules,
        "seed_urls": sorted(list(set(valid_urls))) # Únicas y ordenadas
    }

    with open(output_yaml, 'w', encoding='utf-8') as f:
        yaml.dump(config_dict, f, allow_unicode=True, sort_keys=False)

    return True, len(valid_urls), len(rejected_urls)
